### PR TITLE
Update dependecies

### PR DESCRIPTION
**Pull request by rochal**
Update depencies

### CODE REVIEW

**Comment by bardzusny** [comment]
Hey there @rochal , thanks!

I'll happily merge this - seems like good excuse for new major release, even if just because of Restify 4 (which has some clearly breaking changes).

One thing that may sound a little funny :) but holds me back from getting this in right away - `package.json` `engines` and Node.JS version to use by Travis (`.travis.yml`). 0.10 is really old already; but it's the one pointed at by `swaggerize-express`, which I'm trying pretty hard to stay in sync with. What do you think? What about proposing update of dependencies over there as well? (Even if just Node.JS version - 0.10? Really? :) ).

**Comment by ghost** [comment]
+1

And it would be nice to have also support for newer peerDependencies if possible:
`"peerDependencies": {
    "restify": "^4.0.2"
  }`

**Comment by rochal** [comment]
Whats the news on this one? Node 6 is around the corner.

**Comment by rockebee** [comment]
Hi @bardzusny, do you see any chance to get this (or an even further upgraded) PR as well as #4 in to swaggerize-restify at some point? It does not seem that swaggerize-express is maintained anymore, so I would not bet on getting it done there as well ...

I'd really love to see some updates for swaggerize-restify, as quite a lot has happened around (Restify 7, Node.js 9, OpenAPI 3.0).

**Pull request closed without merging**
